#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Retakeem.Resource", IsApplication=true)]

namespace Retakeem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Actualite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Bouton_choix_aleatoire = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Chaise = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int clap_board = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Classement = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Connexion = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Continuer = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Jouer = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Options = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Retakem_nom = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int RetakemLogo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Roulot_sur_le_cote_du_menu = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Terminer = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int Continuer = 2131165193;
			
			// aapt resource value: 0x7f070012
			public const int Record = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int Replay = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int abandonner = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int date = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int editText1 = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int editText2 = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int email = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int imageButton1 = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int imageView1 = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int linearLayoutbottom = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int linearLayouttop = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int password = 2131165186;
			
			// aapt resource value: 0x7f070011
			public const int surface = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int tableLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int tableRow1 = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int tableRow2 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int tableRow3 = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int videoView1 = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Inscription = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LecteurVideoPrise = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuConnexion = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuPrincipal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int VideoPrise = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
